apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testbench.fullname" . }}-backend
  labels: {{- include "testbench.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- if .Values.mcp.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testbench.fullname" . }}-mcp
  labels: {{- include "testbench.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "testbench.fullname" . }}-frontend
  labels: {{- include "testbench.labels" . | nindent 4 }}
automountServiceAccountToken: false
